### ISSUE TITLE
Cannot install pug-in

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#19]
@serverfire A partner is complaining about not being able to install the plug in. See screen shot of error.
Any idea please?

![screenshot](https://cloud.githubusercontent.com/assets/3107052/6713343/f6dac6fe-cd91-11e4-9176-95cffe189af3.png)

**Comment by serverfire** [comment]
@libreliodev 
Either they're using a old version of the plugin or It's an error caused by another error.
So this message is not helping.

What's their wordpress version?
What other plugins They're using?

I'll try to remake that environment, If i couldn't we may have to make some tests on their site.

**Comment by serverfire** [comment]
@libreliodev It maybe `access_keys_missing` error.
I should set some error handlers for that.

**Comment by serverfire** [comment]
@libreliodev This is it `access_keys_missing`. I'll push fix soon.

**Comment by libreliodev** [comment]
@serverfire Many thanks.

**Comment by serverfire** [comment]
@libreliodev Fixed

**Comment by libreliodev** [comment]
@serverfire So, you added some error handlers, but there was no bug, correct?

**Comment by serverfire** [comment]
We can call it bug. Since it's not correct behavior.

**Comment by libreliodev** [comment]
Thanks again.
